steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echfo "****************************"
        echo "$BRANCH_NAME"
        echo "****************************"
